# -*- coding: utf-8 -*-
"""Azure_D_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJHJXVS5MVQf01Gy7oYGGp53odwMTKm4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Dataset.csv")
df.head()

df.shape
df.info()

df['timestamp']

df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

df['timestamp']

df = df.sort_values('timestamp').reset_index(drop=True)

df

df['region'] = (
    df['region']
    .str.lower()
    .str.strip()
    .str.replace(" ", "-", regex=False)
)

df['region'] = df['region'].replace({
    'us-east': 'US-East',
    'us-west': 'US-West',
    'europe-north': 'Europe-North',
    'india-south': 'India-South'
})

df = df.drop_duplicates()

df

df.isnull().sum()

df['usage_units']

df['usage_units'] = df['usage_units'].interpolate()

df['usage_units']

df['cost_usd'] = df['cost_usd'].fillna(
    df['cost_usd'].mean()
)

df['cost_usd'].isnull().sum()

df

df['availability_pct'] = df['availability_pct'].ffill()

df['economic_index'] = df['economic_index'].interpolate()
df['market_demand_index'] = df['market_demand_index'].interpolate()
df['internet_traffic_index'] = df['internet_traffic_index'].interpolate()

df.isnull().sum()

df.to_csv("azure_demand_module1_cleaned.csv", index=False)
print("Data Cleaning & Preparation Completed ")

daily_usage = df.groupby('timestamp')['usage_units'].mean()
region_usage = df.groupby('region')['usage_units'].mean()
service_usage = df.groupby('service_type')['usage_units'].mean()
df['capacity_utilization_pct'] = (
    df['usage_units'] / df['provisioned_capacity']
) * 100

plt.figure(figsize=(18,12))
plt.subplot(2, 3, 1)
plt.plot(daily_usage.index, daily_usage.values)
plt.title("Demand Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Usage Units")
plt.grid(True)
plt.subplot(2, 3, 2)
region_usage.plot(kind='bar')
plt.title("Average Demand by Region")
plt.xlabel("Region")
plt.ylabel("Usage Units")
plt.grid(axis='y')
plt.subplot(2, 3, 3)
service_usage.plot(kind='bar')
plt.title("Demand by Service Type")
plt.ylabel("Usage Units")
plt.grid(axis='y')
plt.subplot(2, 3, 4)
plt.hist(df['capacity_utilization_pct'], bins=30)
plt.title("Capacity Utilization Distribution")
plt.xlabel("Utilization (%)")
plt.ylabel("Frequency")
plt.grid(True)
plt.subplot(2, 3, 5)
plt.scatter(df['usage_units'], df['cost_usd'], alpha=0.5)
plt.title("Cost vs Usage")
plt.xlabel("Usage Units")
plt.ylabel("Cost (USD)")
plt.grid(True)
plt.subplot(2, 3, 6)
plt.scatter(df['economic_index'], df['usage_units'], alpha=0.5)
plt.title("Economic Index vs Demand")
plt.xlabel("Economic Index")
plt.ylabel("Usage Units")
plt.grid(True)
plt.tight_layout()
plt.show()

