# -*- coding: utf-8 -*-
"""Azure_D_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xI0HVPACEVC18IKjHJFBkm5TABmdVs9d
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(list(uploaded.keys())[0])
print(df.head())

print(df.columns)

['timestamp', 'region', 'service_type', 'usage_units',
 'provisioned_capacity', 'cost_usd', 'availability_pct',
 'economic_index', 'market_demand_index', 'internet_traffic_index']

df['timestamp'] = pd.to_datetime(df['timestamp'], dayfirst=True)
df = df.sort_values('timestamp')
df.set_index('timestamp', inplace=True)
df = df.fillna(method='ffill')

def create_features(data):
    df = data.copy()
    df['lag1'] = df['usage_units'].shift(1)
    df['lag2'] = df['usage_units'].shift(2)
    df['lag3'] = df['usage_units'].shift(3)
    df['rolling_mean'] = df['usage_units'].rolling(3).mean()
    df['day'] = df.index.day
    df['month'] = df.index.month
    df['dayofweek'] = df.index.dayofweek
    df = df.dropna()
    return df

train_size = int(len(df) * 0.8)
train = df.iloc[:train_size]
test = df.iloc[train_size:]

X_train = train_feat.drop('usage_units', axis=1)
y_train = train_feat['usage_units']
X_test = test_feat.drop('usage_units', axis=1)
y_test = test_feat['usage_units']

train_feat = create_features(train)
test_feat = create_features(test)
train_feat = pd.get_dummies(train_feat, columns=['region', 'service_type'])
test_feat = pd.get_dummies(test_feat, columns=['region', 'service_type'])
train_feat, test_feat = train_feat.align(test_feat, join='left', axis=1, fill_value=0)
X_train = train_feat.drop('usage_units', axis=1)
y_train = train_feat['usage_units']
X_test = test_feat.drop('usage_units', axis=1)
y_test = test_feat['usage_units']

from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
bias = np.mean(y_pred - y_test)

print("MAE:", mae)
print("RMSE:", rmse)
print("Bias:", bias)

plt.figure()
plt.plot(y_test.index, y_test.values, label="Actual")
plt.plot(y_test.index, y_pred, label="Predicted")
plt.legend()
plt.title("XGBoost Demand Prediction")
plt.show()

