# -*- coding: utf-8 -*-
"""Azure_D_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6ZS_lAZYOHMfQ9K1_TGdte_Ub2rj-Ac
"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import joblib
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("/content/Dataset.csv")
df.head()
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['hour'] = df['timestamp'].dt.hour
df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['weekday'] = df['timestamp'].dt.weekday

df['lag1'] = df['usage'].shift(1)
df['lag2'] = df['usage'].shift(2)
df['rolling_mean'] = df['usage'].rolling(3).mean()

df = df.dropna()
X = df[['hour','day','month','weekday','lag1','lag2','rolling_mean']]
y = df['usage']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

model = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6)
model.fit(X_train, y_train)
joblib.dump(model, "model.pkl")
files.download("model.pkl")
from fastapi import FastAPI
import joblib
import pandas as pd

app = FastAPI()

model = joblib.load("model.pkl")

@app.get("/")
def home():
    return {"message": "XGBoost API running"}

@app.post("/predict")
def predict(data: dict):
    df = pd.DataFrame([data])
    prediction = model.predict(df)
    return {"prediction": float(prediction[0])}
    pip install fastapi uvicorn
uvicorn app:app --reload
import streamlit as st
import requests

st.title("Demand Forecast App")

hour = st.number_input("Hour")
day = st.number_input("Day")
month = st.number_input("Month")
weekday = st.number_input("Weekday")
lag1 = st.number_input("Lag1")
lag2 = st.number_input("Lag2")
rolling_mean = st.number_input("Rolling Mean")

if st.button("Predict"):
    data = {
        "hour": hour,
        "day": day,
        "month": month,
        "weekday": weekday,
        "lag1": lag1,
        "lag2": lag2,
        "rolling_mean": rolling_mean
    }

    response = requests.post("YOUR_API_URL/predict", json=data)
    st.write("Prediction:", response.json()["prediction"])