# -*- coding: utf-8 -*-
"""Azure_D_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NMy3u2M-z4JqWlFCICwBycGFyHQyOT6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Dataset.csv")

df

df['timestamp'] = pd.to_datetime(df['timestamp'], dayfirst=True, errors='coerce')
df = df.dropna(subset=['timestamp']) # Ensure timestamp is valid
df = df.sort_values('timestamp').reset_index(drop=True)

df

df['region'] = (
    df['region']
    .str.lower()
    .str.strip()
    .str.replace(" ", "-", regex=False)
)
df['region'] = df['region'].replace({
    'us-east': 'US-East',
    'us-west': 'US-West',
    'europe-north': 'Europe-North',
    'india-south': 'India-South'
})

df

df = df.drop_duplicates()

# Missing values handling
df['usage_units'] = df['usage_units'].interpolate()
df['cost_usd'] = df['cost_usd'].fillna(df['cost_usd'].mean())
df['availability_pct'] = df['availability_pct'].ffill()
df['economic_index'] = df['economic_index'].interpolate()
df['market_demand_index'] = df['market_demand_index'].interpolate()
df['internet_traffic_index'] = df['internet_traffic_index'].interpolate()

df

df['hour'] = df['timestamp'].dt.hour
df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['year'] = df['timestamp'].dt.year
df['day_of_week'] = df['timestamp'].dt.dayofweek
df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

df

group_cols = ['region', 'service_type']

df = df.sort_values(by=group_cols + ['timestamp'])

df['usage_lag_1'] = df.groupby(group_cols)['usage_units'].shift(1)
df['usage_lag_7'] = df.groupby(group_cols)['usage_units'].shift(7)
df

df['usage_rolling_mean_7'] = df.groupby(group_cols)['usage_units'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
df['usage_rolling_std_7'] = df.groupby(group_cols)['usage_units'].transform(lambda x: x.rolling(window=7, min_periods=1).std())
df

df['usage_spike'] = (df['usage_units'] > (df['usage_rolling_mean_7'] * 1.5)).astype(int)

df['capacity_utilization_pct'] = (df['usage_units'] / df['provisioned_capacity']) * 100

df.to_csv("azure_demand_features.csv", index=False)

df

plt.subplot(2, 2, 1)
df.groupby('day_of_week')['usage_units'].mean().plot(kind='bar', color='skyblue')
plt.title('Average Usage by Day of Week (0=Mon, 6=Sun)')
plt.xlabel('Day of Week')
plt.ylabel('Avg Usage Units')

plt.subplot(2, 2, 3)
sample_df = df[(df['region'] == 'US-East') & (df['service_type'] == 'Compute')].tail(60)
plt.plot(sample_df['timestamp'], sample_df['usage_units'], label='Actual Usage', alpha=0.7)
plt.plot(sample_df['timestamp'], sample_df['usage_rolling_mean_7'], label='7-Day Rolling Mean', linestyle='--')
plt.title('Usage vs Rolling Mean (US-East Compute - Last 60 Days)')
plt.legend()
plt.xticks(rotation=45)

plt.subplot(2, 2, 4)
spike_counts = df.groupby('timestamp')['usage_spike'].sum()
plt.plot(spike_counts.index, spike_counts.values, color='red')
plt.title('Total Usage Spikes Across All Regions')
plt.xlabel('Date')
plt.ylabel('Count of Spikes')

plt.tight_layout()
plt.savefig('feature_engineering_analysis.png')

plt.subplot(4, 2, 8)
plt.scatter(df['usage_units'], df['cost_usd'], alpha=0.3, color='tab:grey')
plt.title("Cost vs Usage Correlation", fontsize=16)
plt.xlabel("Usage Units")
plt.ylabel("Cost (USD)")
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.savefig("final_combined_demand_dashboard.png")
plt.show()

print(df[['timestamp', 'usage_units', 'usage_lag_1', 'usage_rolling_mean_7', 'usage_spike', 'is_weekend']].head(10))
print("\nNew columns added:", [col for col in df.columns if col not in pd.read_csv("Dataset.csv").columns])

