# -*- coding: utf-8 -*-
"""Azure_link

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jNnd3uFbUvVBr5FPis5_qPZ9fXzQjcV
"""

import streamlit as st
import requests
st.title("Demand Forecasting App (XGBoost)")
st.write("Enter input features to predict demand")
hour = st.number_input("Hour (0-23)", min_value=0, max_value=23)
day = st.number_input("Day (1-31)", min_value=1, max_value=31)
month = st.number_input("Month (1-12)", min_value=1, max_value=12)
weekday = st.number_input("Weekday (0=Mon, 6=Sun)", min_value=0, max_value=6)
lag1 = st.number_input("Previous Usage (lag1)")
lag2 = st.number_input("Previous Usage (lag2)")
rolling_mean = st.number_input("Rolling Mean")
API_URL = "https://your-api.onrender.com/predict"
if st.button("Predict"):
    data = {
        "hour": hour,
        "day": day,
        "month": month,
        "weekday": weekday,
        "lag1": lag1,
        "lag2": lag2,
        "rolling_mean": rolling_mean
    }
    try:
        response = requests.post(API_URL, json=data)
        result = response.json()

        st.success(f"Predicted Demand: {result['prediction']:.2f}")

    except:
        st.error("Error connecting to API. Check your API URL.")

        API_URL = "https://xgboost-api.onrender.com/predict"